global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@archon.dev'
  smtp_auth_username: 'alerts@archon.dev'
  smtp_auth_password: '${SMTP_PASSWORD}'
  
  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'severity', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-notifications'
  
  routes:
    # Critical alerts get immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # Performance alerts during business hours
    - match:
        category: performance
      receiver: 'performance-alerts'
      active_time_intervals:
        - business_hours
    
    # Infrastructure alerts
    - match:
        category: infrastructure
      receiver: 'infrastructure-alerts'
    
    # Business logic alerts
    - match:
        category: business
      receiver: 'business-alerts'
    
    # External service alerts
    - match:
        category: external
      receiver: 'external-service-alerts'

# Time intervals
time_intervals:
  - name: business_hours
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '17:00'
        weekdays: ['monday:friday']
        location: 'America/New_York'

# Inhibition rules
inhibit_rules:
  # Inhibit lower severity alerts when critical alerts are firing
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['alertname', 'service']
  
  # Inhibit individual service alerts when service is down
  - source_matchers:
      - alertname="ServiceAvailabilityLow"
    target_matchers:
      - service=~".+"
    equal: ['service']

# Notification receivers
receivers:
  - name: 'default-notifications'
    slack_configs:
      - channel: '#archon-alerts'
        title: 'Archon Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#archon-critical'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          @here CRITICAL ALERT REQUIRES IMMEDIATE ATTENTION
          
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true
    
    email_configs:
      - to: 'oncall@archon.dev'
        subject: '🚨 CRITICAL: Archon {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT - IMMEDIATE ACTION REQUIRED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true

  - name: 'performance-alerts'
    slack_configs:
      - channel: '#archon-performance'
        title: '⚡ Performance Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true

  - name: 'infrastructure-alerts'
    slack_configs:
      - channel: '#archon-infrastructure'
        title: '🏗️ Infrastructure Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true

  - name: 'business-alerts'
    slack_configs:
      - channel: '#archon-business'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true

  - name: 'external-service-alerts'
    slack_configs:
      - channel: '#archon-external'
        title: '🌐 External Service Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true